permalink: /blog/:title/
title: Fish-shell Blog
id: https://fishshell.com/blog
plugins:
    - jekyll-feed
feed:
    title: Fish-shell Blog
    id: https://fishshell.com/blog
    path: /blog/feed.xml
    author: Fish-shell authors
